project_id = "xliplxqwvvtmgfovznzf"

[functions.create-client]
verify_jwt = true

[functions.update-coin-prices]
verify_jwt = false

[functions.update-fx-rates]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false
