/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminMuralRouteImport } from './routes/admin.mural'
import { Route as AdminCotacoesRouteImport } from './routes/admin.cotacoes'
import { Route as AdminClientesIndexRouteImport } from './routes/admin.clientes.index'
import { Route as AdminClientesClientIdIndexRouteImport } from './routes/admin.clientes.$clientId.index'
import { Route as AdminClientesClientIdFundosFundIdRouteImport } from './routes/admin.clientes.$clientId.fundos.$fundId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMuralRoute = AdminMuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCotacoesRoute = AdminCotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesIndexRoute = AdminClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesClientIdIndexRoute =
  AdminClientesClientIdIndexRouteImport.update({
    id: '/clientes/$clientId/',
    path: '/clientes/$clientId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminClientesClientIdFundosFundIdRoute =
  AdminClientesClientIdFundosFundIdRouteImport.update({
    id: '/clientes/$clientId/fundos/$fundId',
    path: '/clientes/$clientId/fundos/$fundId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/admin/cotacoes': typeof AdminCotacoesRoute
  '/admin/mural': typeof AdminMuralRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/clientes/$clientId/': typeof AdminClientesClientIdIndexRoute
  '/admin/clientes/$clientId/fundos/$fundId': typeof AdminClientesClientIdFundosFundIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/admin/cotacoes': typeof AdminCotacoesRoute
  '/admin/mural': typeof AdminMuralRoute
  '/admin': typeof AdminIndexRoute
  '/admin/clientes': typeof AdminClientesIndexRoute
  '/admin/clientes/$clientId': typeof AdminClientesClientIdIndexRoute
  '/admin/clientes/$clientId/fundos/$fundId': typeof AdminClientesClientIdFundosFundIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/admin/cotacoes': typeof AdminCotacoesRoute
  '/admin/mural': typeof AdminMuralRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/clientes/$clientId/': typeof AdminClientesClientIdIndexRoute
  '/admin/clientes/$clientId/fundos/$fundId': typeof AdminClientesClientIdFundosFundIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/cotacoes'
    | '/admin/mural'
    | '/admin/'
    | '/admin/clientes/'
    | '/admin/clientes/$clientId/'
    | '/admin/clientes/$clientId/fundos/$fundId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/admin/cotacoes'
    | '/admin/mural'
    | '/admin'
    | '/admin/clientes'
    | '/admin/clientes/$clientId'
    | '/admin/clientes/$clientId/fundos/$fundId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/cotacoes'
    | '/admin/mural'
    | '/admin/'
    | '/admin/clientes/'
    | '/admin/clientes/$clientId/'
    | '/admin/clientes/$clientId/fundos/$fundId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mural': {
      id: '/admin/mural'
      path: '/mural'
      fullPath: '/admin/mural'
      preLoaderRoute: typeof AdminMuralRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cotacoes': {
      id: '/admin/cotacoes'
      path: '/cotacoes'
      fullPath: '/admin/cotacoes'
      preLoaderRoute: typeof AdminCotacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/': {
      id: '/admin/clientes/'
      path: '/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AdminClientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/$clientId/': {
      id: '/admin/clientes/$clientId/'
      path: '/clientes/$clientId'
      fullPath: '/admin/clientes/$clientId/'
      preLoaderRoute: typeof AdminClientesClientIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/$clientId/fundos/$fundId': {
      id: '/admin/clientes/$clientId/fundos/$fundId'
      path: '/clientes/$clientId/fundos/$fundId'
      fullPath: '/admin/clientes/$clientId/fundos/$fundId'
      preLoaderRoute: typeof AdminClientesClientIdFundosFundIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCotacoesRoute: typeof AdminCotacoesRoute
  AdminMuralRoute: typeof AdminMuralRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientesIndexRoute: typeof AdminClientesIndexRoute
  AdminClientesClientIdIndexRoute: typeof AdminClientesClientIdIndexRoute
  AdminClientesClientIdFundosFundIdRoute: typeof AdminClientesClientIdFundosFundIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCotacoesRoute: AdminCotacoesRoute,
  AdminMuralRoute: AdminMuralRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientesIndexRoute: AdminClientesIndexRoute,
  AdminClientesClientIdIndexRoute: AdminClientesClientIdIndexRoute,
  AdminClientesClientIdFundosFundIdRoute:
    AdminClientesClientIdFundosFundIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
