/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppRendimentosRouteImport } from './routes/app.rendimentos'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppMuralRouteImport } from './routes/app.mural'
import { Route as AppFuturosRouteImport } from './routes/app.futuros'
import { Route as AppFundosRouteImport } from './routes/app.fundos'
import { Route as AppDocumentosRouteImport } from './routes/app.documentos'
import { Route as AdminMuralRouteImport } from './routes/admin.mural'
import { Route as AdminCotacoesRouteImport } from './routes/admin.cotacoes'
import { Route as AdminClientesIndexRouteImport } from './routes/admin.clientes.index'
import { Route as AdminClientesClientIdIndexRouteImport } from './routes/admin.clientes.$clientId.index'
import { Route as AdminClientesClientIdFundosFundIdRouteImport } from './routes/admin.clientes.$clientId.fundos.$fundId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppRendimentosRoute = AppRendimentosRouteImport.update({
  id: '/rendimentos',
  path: '/rendimentos',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppMuralRoute = AppMuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => AppRoute,
} as any)
const AppFuturosRoute = AppFuturosRouteImport.update({
  id: '/futuros',
  path: '/futuros',
  getParentRoute: () => AppRoute,
} as any)
const AppFundosRoute = AppFundosRouteImport.update({
  id: '/fundos',
  path: '/fundos',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AdminMuralRoute = AdminMuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCotacoesRoute = AdminCotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesIndexRoute = AdminClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesClientIdIndexRoute =
  AdminClientesClientIdIndexRouteImport.update({
    id: '/clientes/$clientId/',
    path: '/clientes/$clientId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminClientesClientIdFundosFundIdRoute =
  AdminClientesClientIdFundosFundIdRouteImport.update({
    id: '/clientes/$clientId/fundos/$fundId',
    path: '/clientes/$clientId/fundos/$fundId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/cotacoes': typeof AdminCotacoesRoute
  '/admin/mural': typeof AdminMuralRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/fundos': typeof AppFundosRoute
  '/app/futuros': typeof AppFuturosRoute
  '/app/mural': typeof AppMuralRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/rendimentos': typeof AppRendimentosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/clientes/$clientId/': typeof AdminClientesClientIdIndexRoute
  '/admin/clientes/$clientId/fundos/$fundId': typeof AdminClientesClientIdFundosFundIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/cotacoes': typeof AdminCotacoesRoute
  '/admin/mural': typeof AdminMuralRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/fundos': typeof AppFundosRoute
  '/app/futuros': typeof AppFuturosRoute
  '/app/mural': typeof AppMuralRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/rendimentos': typeof AppRendimentosRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/clientes': typeof AdminClientesIndexRoute
  '/admin/clientes/$clientId': typeof AdminClientesClientIdIndexRoute
  '/admin/clientes/$clientId/fundos/$fundId': typeof AdminClientesClientIdFundosFundIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/cotacoes': typeof AdminCotacoesRoute
  '/admin/mural': typeof AdminMuralRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/fundos': typeof AppFundosRoute
  '/app/futuros': typeof AppFuturosRoute
  '/app/mural': typeof AppMuralRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/rendimentos': typeof AppRendimentosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/clientes/$clientId/': typeof AdminClientesClientIdIndexRoute
  '/admin/clientes/$clientId/fundos/$fundId': typeof AdminClientesClientIdFundosFundIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/cotacoes'
    | '/admin/mural'
    | '/app/documentos'
    | '/app/fundos'
    | '/app/futuros'
    | '/app/mural'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app/rendimentos'
    | '/admin/'
    | '/app/'
    | '/admin/clientes/'
    | '/admin/clientes/$clientId/'
    | '/admin/clientes/$clientId/fundos/$fundId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/cotacoes'
    | '/admin/mural'
    | '/app/documentos'
    | '/app/fundos'
    | '/app/futuros'
    | '/app/mural'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app/rendimentos'
    | '/admin'
    | '/app'
    | '/admin/clientes'
    | '/admin/clientes/$clientId'
    | '/admin/clientes/$clientId/fundos/$fundId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/cotacoes'
    | '/admin/mural'
    | '/app/documentos'
    | '/app/fundos'
    | '/app/futuros'
    | '/app/mural'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app/rendimentos'
    | '/admin/'
    | '/app/'
    | '/admin/clientes/'
    | '/admin/clientes/$clientId/'
    | '/admin/clientes/$clientId/fundos/$fundId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/rendimentos': {
      id: '/app/rendimentos'
      path: '/rendimentos'
      fullPath: '/app/rendimentos'
      preLoaderRoute: typeof AppRendimentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mural': {
      id: '/app/mural'
      path: '/mural'
      fullPath: '/app/mural'
      preLoaderRoute: typeof AppMuralRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/futuros': {
      id: '/app/futuros'
      path: '/futuros'
      fullPath: '/app/futuros'
      preLoaderRoute: typeof AppFuturosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fundos': {
      id: '/app/fundos'
      path: '/fundos'
      fullPath: '/app/fundos'
      preLoaderRoute: typeof AppFundosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documentos': {
      id: '/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/mural': {
      id: '/admin/mural'
      path: '/mural'
      fullPath: '/admin/mural'
      preLoaderRoute: typeof AdminMuralRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cotacoes': {
      id: '/admin/cotacoes'
      path: '/cotacoes'
      fullPath: '/admin/cotacoes'
      preLoaderRoute: typeof AdminCotacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/': {
      id: '/admin/clientes/'
      path: '/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AdminClientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/$clientId/': {
      id: '/admin/clientes/$clientId/'
      path: '/clientes/$clientId'
      fullPath: '/admin/clientes/$clientId/'
      preLoaderRoute: typeof AdminClientesClientIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/$clientId/fundos/$fundId': {
      id: '/admin/clientes/$clientId/fundos/$fundId'
      path: '/clientes/$clientId/fundos/$fundId'
      fullPath: '/admin/clientes/$clientId/fundos/$fundId'
      preLoaderRoute: typeof AdminClientesClientIdFundosFundIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCotacoesRoute: typeof AdminCotacoesRoute
  AdminMuralRoute: typeof AdminMuralRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientesIndexRoute: typeof AdminClientesIndexRoute
  AdminClientesClientIdIndexRoute: typeof AdminClientesClientIdIndexRoute
  AdminClientesClientIdFundosFundIdRoute: typeof AdminClientesClientIdFundosFundIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCotacoesRoute: AdminCotacoesRoute,
  AdminMuralRoute: AdminMuralRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientesIndexRoute: AdminClientesIndexRoute,
  AdminClientesClientIdIndexRoute: AdminClientesClientIdIndexRoute,
  AdminClientesClientIdFundosFundIdRoute:
    AdminClientesClientIdFundosFundIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppFundosRoute: typeof AppFundosRoute
  AppFuturosRoute: typeof AppFuturosRoute
  AppMuralRoute: typeof AppMuralRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppRendimentosRoute: typeof AppRendimentosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDocumentosRoute: AppDocumentosRoute,
  AppFundosRoute: AppFundosRoute,
  AppFuturosRoute: AppFuturosRoute,
  AppMuralRoute: AppMuralRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppRendimentosRoute: AppRendimentosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
